### ISSUE TITLE
remove `:root` limitation by injecting rules with new declarations that just contains modified properties.

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-properties#1]
ref https://github.com/reworkcss/rework-vars/issues/30

**Comment by kevinSuttle** [comment]
Oh man. This is a bummer, but thanks for all the work that went into figuring this out up until this point. Hopefully we'll be able to use scope-defined custom properties soon.

**Comment by kevinSuttle** [comment]
This also seems to mean that you cannot import CSS files that use `:root` declarations, unless there's an implied PostCSS plugin that I should be using like https://github.com/postcss/postcss-import. 

e.g. 

```css
/* theme.css */
:root {
  --HighlightColor: #3acfb6;
}
```

```css
/* fonts.css */
import "./Theme.css"; 

.cardTitle {
  color: var(--HighlightColor)
}
```

Outputs:
```
variable '--HighlightColor' is undefined and used without a fallback
```
