### ISSUE TITLE
Better progressive enhancement control

### ISSUE THREAD

**Issue by keithjgrant** [postcss/postcss-custom-properties#107]
I have a scenario where I want to use custom properties natively for browsers that support it, with a reasonable fallback for those than don't. But I don't think this is possible with the plugin:

```css
// input:
.nav {
  --nav-color: blue;
  background-color: var(--nav-color, white);
}

// actual result:
.nav {
  --nav-color: blue;
  background-color: white;
}

// desired result:
.nav {
  --nav-color: blue;
  background-color: white;
  background-color: var(--nav-color, white);
}
```

I *know* the plugin can’t convert this, and I don’t want it to. But I want my authored styles to pass through to those browsers that can handle it.

Additionally, this throws a warning that I’d like to be able to suppress: “Custom property ignored: not scoped to the top-level :root element (.nav { ... --nav-color: ... })”
