### ISSUE TITLE
var(--property) warnings not triggered by postcss when the variable references a variable 

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#112]
Within commit ` 0a687c5f23355050bce870d4c83e207f3986444c` of the [variables-colors](https://github.com/superflycss/variables-colors/commit/0a687c5f23355050bce870d4c83e207f3986444c) repository I have the following code snippet in the file [src/main/css/index.css](https://github.com/superflycss/variables-colors/blob/master/src/main/css/index.css).  

``` css
/* 1 */
:root {
  --color-white:                   #fff;
  --color-text:                    var(--color-dark-gray);
  --color-text-muted:              var(--color-light-gray);
  --color-link:                    var(--color-primary);
  --color-link-hover:              color(var(--color-link) blackness(var(--percentage-link-hover)));
  --color-abbr-border:             var(--color-gray-light);
  --color-table-background:        transparent;
  --color-table-background-accent: #f9f9f9;
  --color-table-background-hover:  #f5f5f5;
  --color-table-background-active: var(--color-table-background-hover);
  --color-table-border-color:      var(--color-gray-lighter);
}
```

The color variables referenced here come from the `@import ./browser/` import, however there is no such variable as `--color-gray-light`.  However during the build postcss does not warn that this variable does not exist.

It does however warn when this module is included in other modules.  For example the [@superflycss/foundation](https://github.com/superflycss/foundation) references the [@superflycss/foundation](https://github.com/superflycss/variables-colors) module, and when building foundation I noticed the `--color-gray-light` variable did not exist.  

I'm going to rename the color to correct the module, and bump the minor version number, so if you want to see this in action, make sure you use `variables-colors@3.0.3` as the `foundation` dependency when building foundation.

``` console
git clone https://github.com/superflycss/foundation
cd foundation
npm i -g @superflycss/cli
sfc build
```
