### ISSUE TITLE
PostCSS log var(--property) warnings not triggered by postcss when the variable references an undeclared variable

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#113]
This [issue references the previous issue I filed with the same title](https://github.com/postcss/postcss-custom-properties/issues/112), BUT I will provide a much simpler explanation.  If you have some CSS variables declared like this:

```css
:root {
    --color-gray-light: blue;
}
  
:root {
    --color-abbr-border:             var(--color-light-gray);
  }
```
PostCSS will not warn when building this.  However if this is packaged up as a module, and imported by an upstream project, then postcss will warn that it cannot resolve the variable `--color-light-gray`;
