### ISSUE TITLE
Duplicate Variables using `postcss-custom-properties`

### ISSUE THREAD

**Issue by josephschmitt** [postcss/postcss-custom-properties#114]
When mixing and matching variables you declare in your source files along with `appendVariables` and `preserve`, those vars get output twice: once from your source, and once appended to the bottom. Shouldn't `appendVariables` only be appending those that were passed in via the plugin's `variables` option? I don't understand the point of appending it again at the bottom. Am I missing something?

Test case showing the issue here:
https://github.com/josephschmitt/custom-properties-append-vars-duplicates

Source setup:
```css
:root {
  --myColor: red;
}

.my-component {
  color: var(--myColor);
  background: var(--myBackgroundColor);
}
```
`postcss.config.js`:
```js
module.exports = {
  plugins: [
    require('postcss-custom-properties')({
      preserve: true,
      appendVariables: true,
      variables: {
        myBackgroundColor: 'lightgray'
      }
    })
  ]
};
```

## Expected Result

Running through the `postcss-custom-properties` plugin with `preserve` and `appendVariables` produces an output file with the locally declared variables preserved, and the variables passed in via the plugin appended at the end of the file:

```css
:root {
  --myColor: red;
}

.my-component {
  color: red;
  color: var(--myColor);
  background: lightgray;
  background: var(--myBackgroundColor);
}

:root {
  --myBackgroundColor: lightgray;
}
```

## Actual Result

The output file correctly preserves the local variable and it appends the variable passed in via the config, but then it also outputs the local variable _again_ appended to the bottom of the file. This is wasteful, and gets especially bad in large projects with lots of declared variables:

```css
:root {
  --myColor: red;
}

.my-component {
  color: red;
  color: var(--myColor);
  background: lightgray;
  background: var(--myBackgroundColor);
}

:root {
  --myColor: red;
  --myBackgroundColor: lightgray;
}
```
