### ISSUE TITLE
implementation idea for cascading variables

### ISSUE THREAD

**Issue by Nemo64** [postcss/postcss-custom-properties#115]
So, I just had this idea on how cascading variables might be implementable. It would look like this:

```css
.element--red {
    --color: red;
}
.element {
    background-color: var(--color);
}

/* becomes */

.element--red { /* may still contain the var definition based on settings */ }

.element { /* may still contain the property based on fallback etc. */ }

.element--red.element,
.element--red .element {
    background-color: red;
}
```

Now I know that this has a lot of issues. Selector merging isn't always straight forward and there are also priority rules so this isn't fool proof. Property definitions may need to be limited to classes to save a lot of headaches.

And it becomes really complicated if more than 1 variable is used within one property. A gradient like `background-image: linear-gradient(var(--color1), var(--color2));` might need a lot more than 1 rule based on how often the custom-properties are defined. Basically every possible combination must be defined.

But even with those caveats and if i'm not overlooking something big here, this would allow one to use custom properties to the full extend. Which would be awesome.

So what am i overlooking? 🤔

**Comment by Nemo64** [comment]
Here is a more complicated case:

```css
.color {
    --color: red;
}

.nav-item  .nav-link {
    background-color: var(--color);
}

/* becomes */

.color .nav-item  .nav-link,
.color.nav-item .nav-link,
.nav-item .color .nav-link,
.nav-item .color.nav-link {
    background-color: red;
}
```

And while writing this i noticed this problem:
```css
div {
    background-color: var(--color);
}

.color div { /* this has a higher priority as "div" */
    background-color: red;
}

div { /* so this wouldn't override the color since the priority of a type selector is lower */
    background-color: blue;
}
```
But this would work again:
```css
[attr] {
    background-color: var(--color);
}

.color [attr] { /* attribute selectors have a higher priority than class selectors so this inherits that priority */
    background-color: red;
}

[att] { /* this still has the priority of an attribute selector */
    background-color: blue;
}
```

So as far as i know, the priority order is

1. universal selector
2. type selector
3. class selector
4. ... everything else

So by limiting the the property definition to classes, it would only do problems if you override a `1:1` rule like overwriting `div` with `div` since any more specific rule has a higher priority, ergo at least the same priority as the class selector...
