### ISSUE TITLE
Not replacing variables defined in a class

### ISSUE THREAD

**Issue by Fenntasy** [postcss/postcss-custom-properties#121]
Hello,

I may be wrong in my interpretation of this plugin but I don't understand what it does when we use CSS custom properties outside of a `:root` definition.

Here is a test file:

```javascript
const postCSSCustomProperties = require('postcss-custom-properties');

const CSS = `
:root {
  --color: red;
}
body {
  background: var(--color);
}
.myClass {
  --othercolor: blue;
  background: var(--othercolor);
}
.myClass .mySubClass {
  background: var(--othercolor);
}
.myClass .mySubClass {
  border-color: var(--color);
}
`;

const result = postCSSCustomProperties.process(CSS);
console.log(result.css);
```

And here is the output:

```css
:root {
  --color: red;
}
body {
  background: red;
  background: var(--color);
}
.myClass {
  --othercolor: blue;
  background: var(--othercolor);
  background: var(--othercolor);
}
.myClass .mySubClass {
  background: var(--othercolor);
  background: var(--othercolor);
}
.myClass .mySubClass {
  border-color: red;
  border-color: var(--color);
}
```

I like that it keeps the use of `var(--color)` for browsers that can deal with it but just prefix it with a safe value.
But I don't understand why it does not work with `--othercolor`, especially when it duplicates the lines.

Is there something I'm missing or is this a bug?
