### ISSUE TITLE
No access to the variable declared in another file

### ISSUE THREAD

**Issue by vladimir-kondratenko** [postcss/postcss-custom-properties#122]
The plugin doesn't transform variable, declared in another file, to a value. In context of React. I used simple css loader and postcss-preset-env
# INPUT
*component1.css*
```css
:root {
   --color: red;
}
```

*component2.css*
```css
* {
   color: var(--color);
}
```

# OUTPUT
```css
* {
   color: var(--color);
   color: var(--color);
}
```

# EXPECTED OUTPUT
```css
 * {
   color: red;
   color: var(--color);
}
```

But if I declared and used a variable in one file it transformed as expected.
Or mb it's correct behavior and I don't understand something :(
Could someone explain?
