### ISSUE TITLE
root containing comments is preserved with preserve: false

### ISSUE THREAD

**Issue by gpoitch** [postcss/postcss-custom-properties#123]
```js
postCSSCustomProperties({
  preserve: false
})
```

```css
:root {
  /* Colors */
  --color: red;
}

h1 {
  color: var(--color);
}

/* becomes */

:root {
  /* Colors */
}

h1 {
  color: red;
}
```
