### ISSUE TITLE
CSS Variable Dependence in Root

### ISSUE THREAD

**Issue by ZachJW34** [postcss/postcss-custom-properties#129]
I was using postcss-custom-properties to produce fallback values for IE theming. Our application has hundreds of color variables, and we have them declared in root. I understand the transforming of the custom properties that contain var() in root, but should CSS variables that depend upon other CSS variables also be transformed and thus produce a duplicate variable declaration?

# Input
```css
:root {
    --color1: red;
    --color2: var(--color1);
    --color3: var(--color2);
    
    background-color: var(--color3);
}
```
# Expected
```css
:root {
    --color1: red;
    --color2: var(--color1);
    --color3: var(--color2);
    
    background-color: red;
    background-color: var(--color3);
}
```
# Actual
```css
:root {
    --color1: red;
    --color2: red;
    --color2: var(--color1);
    --color3: red;
    --color3: var(--color2);
    
    background: red;
    background-color: var(--color3);
}
```
Is this duplication necessary for obtaining the correct fallback values for css variables that depend upon another? If not, should there be an option to not transform css variable declarations?
