### ISSUE TITLE
Allow to filter preserved custom properties

### ISSUE THREAD

**Issue by jiayihu** [postcss/postcss-custom-properties#131]
Due to runtime performance of root current properties on large applications, it would be nice to allow a mix of preserved and removed custom properties. The idea is to remove runtime properties which you want to be static to improve performance, whereas to leave at runtime those who are dynamic such as involved in the theme.

[Article about runtime performance of CSS variables](https://lisilinhart.info/posts/css-variables-performance).

**Comment by jonathantneal** [comment]
This can be accomplished using the `importFrom` feature with `preserve` false.

**Comment by jiayihu** [comment]
It doesn't seem so, but first I'd like to explain better my case. There are two possible scenarios:

1. Specify which custom properties to preserve. From the PR, this can be almost achieved by allowing to pass options to each source in `importFrom`
    ```js
    postcssCustomProperties({
      importFrom: [
        { path: 'path/to/file.css', preserve: true },
        { path: 'and/then/this.js', preserve: false }
    });
    ```

2. Specify which declarations using custom properties to preserve, maybe by using comments:

  ```css
  /* Assuming preserve: true for this source */
  :root {
    --color: red;
  }

  /* postcss-custom-properties-disable preserve */

  h1 {
    color: var(--color);
  }

  /* postcss-custom-properties-enable preserve */

  .themed-box {
    color: var(--color)
  }

  /* becomes */
  :root {
    --color: red;
  }

  h1 {
    color: red;
  }

  .themed-box {
    color: red;
    color: var(--color)
  }
  ``` 

The rational of these requests are to allow tuning performance. Even if runtime custom properties are not changed, they still have an [impact on start-up performance](https://blog.jiayihu.net/css-custom-properties-performance-in-2018/#css-variables-start-up-performance).
