### ISSUE TITLE
Incorrect output when using variable fallbacks

### ISSUE THREAD

**Issue by necolas** [postcss/postcss-custom-properties#14]
This is not the correct expected output:

https://github.com/postcss/postcss-custom-properties/blob/83f6dda366ccd4ef178fa5671bef1a8de823eeee/test/fixtures/substitution-fallback.expected.css#L27

The fallback should only be used as the value of the property when the variable is not defined. It should not appear in the output if the variable was defined.

**Comment by necolas** [comment]
Any chance we can resolve this?

**Comment by MoOx** [comment]
What about a `fallbacks` option (default to `false`) ?

**Comment by necolas** [comment]
Well, the variables should always fallback when a fallback is specified (as per spec). Problem for me is the extra stuff that tries to account for invalid variables by always writing a "fallback" to the CSS output. If you want to add that as an option, sure. Would not use the name 'fallback' though because it will be confusing IMO.

**Comment by MoOx** [comment]
Here are some idea:
- outputFallbacks
- prependFallbacks
- includeFallbacks

**Comment by necolas** [comment]
I don't think it is a fallback though (in the CSS custom prop sense).

**Comment by MoOx** [comment]
No idea on which name to use and I saw `fallback` used in the spec


>  The second argument to the function, if provided, is a fallback value, which is used as the substitution value when the referenced custom property is invalid. 

...

> Attempting to do so makes the declaration invalid at computed-value time, unless a valid fallback is specified. 

...

> 	Note: The syntax of the fallback, like that of custom properties, allows commas. For example, var(--foo, red, blue) defines a fallback of red, blue; that is, anything between the first comma and the end of the function is considered a fallback value.

If you have a better idea, I will take it :)

**Comment by MoOx** [comment]
Here are other proposals:

- invalidFallbacks
- invalidValues
- includeInvalidValues

**Comment by simonsmith** [comment]
Given this code:

``` css
:root {
  --border: 5px solid red;
}

.Thing {
  border: var(--border, 1px solid rgba(255, 0, 0, 0.5));
}
```

I get the following output:

``` css
.Thing {
  border: 1px solid rgba(255, 0, 0, 0.5);
  border: 5px solid red; 
}
```

Surely it should just have the `5px solid red;`? 
I'm inclined to agree with [this comment](https://github.com/postcss/postcss-custom-properties/issues/14#issuecomment-65108395)

**Comment by MoOx** [comment]
See spec quotes https://github.com/postcss/postcss-custom-properties/issues/14#issuecomment-74253983
If "someone", add this

```css
:root {
  --border: 5px;
}
```

You will thank you code to be

```css
.Thing {
  border: 1px solid rgba(255, 0, 0, 0.5);
  border: 5px; /* invalid, skipped by the browser, fallback to the previous value, per spec */ 
}
```

I just need a name to implement this option. I made some proposal but don't get any feedbacks on them. Since I am not going to use this option, I am not in a hurry.

Again, here are some ideas:

- outputFallbacks (default: true)
- prependFallbacks (default: true)
- includeFallbacks (default: true)
- includeInvalidValues  (default: true)
- skipFallbacks (default: false)

**Comment by simonsmith** [comment]
Hmm, this isn't the behaviour I'm seeing in the browser. The spec refers to 'invalid' properties but `border: 5px` isn't invalid.

See here - http://jsbin.com/hudavofaji/1/edit?html,css,output

![screen shot 2015-03-16 at 07 19 04](https://cloud.githubusercontent.com/assets/360703/6661947/c5b9e118-cbac-11e4-9ea6-19bf4f388816.png)

I feel like this overriding behaviour that you have now should be opt-in with a config, not opt-out as it's confusing.

**Comment by MoOx** [comment]
Indeed my example was stupid (so not relevant).
Let consider this one:

```css
:root {
  --border: 5px solid red;
}

.Thing {
  border: var(--border, 1px solid rgba(255, 0, 0, 0.5));
}

/* later*/
:root {
  --border: green; /* or any stupid value like "thing" or "42" */
}
```

**Comment by simonsmith** [comment]
Yeah, I see what you're trying to solve. 

I think the idea of disabling fallbacks via an option is tricky, because I think we need fallbacks (i.e if the property is not there) but having the property written out twice if it is there (to defend against invalid ones) is not ideal.

Interestingly when I tried the code above in Firefox (which apparently [supports custom properties](http://caniuse.com/#search=css%20var)) it just ignored my border entirely and did not fallback (I'm guessing because it was invalid). I'm not sure how closely it has adhered to the spec though.

Maybe the config name could be based around the concept of invalid custom properties, as that is what it feels like it's trying to protect against.

`allowInvalid` or something

**Comment by MoOx** [comment]
Firefox has a very bad support about custom properties (better than nothing, but very buggy).

I was thinking about not ignoring all fallback, but more just adding the last value (valid or not) of all the computed values (fallbacks + last value). Because people that are concerned about this issue just want to avoid extra output. Am I right?

**Comment by simonsmith** [comment]
Okay, so in your example above that would mean I would see `border: green`? This is  with an option flag?

**Comment by MoOx** [comment]
The option can check if the value is valid or not, the option can only choose if we add fallbacks (all computed values) or just the last one.

Consider this example  (with postcss-calc)

```
:root {
  --font-size: 1.2em
}

:root {
  --lineHeight: calc(var(--font-size, 1em) * 1.5);
}

.Thing {
  margin-bottom: var(--lineHeight, 2em)
}
```

You will got

```css
.Thing {
  margin-bottom: 2em;
  margin-bottom: 1.5em;
  margin-bottom: 1.8em
}
```

because we don't know what is valid or not. From what I understand of the specs, this is the closest behavior we can do to follow the specs.

That being said, if like necolas, you don't want too many things in your output, we can add an option to only keep the latest value computed.

**Comment by simonsmith** [comment]
Although it's following the spec I do think being able to have three margin declarations in the output is taking it a bit far. Do you not think most users of this plugin would be confused to see that?

What about making the above an opt in feature instead, like a strict mode?

**Comment by MoOx** [comment]
If you play with fallbacks, that a requirement imo.
If you play with this kind of postcss plugins (in a way that mimic w3c specs) you need to be know what your are dealing with.
A note in the README under the option should be enough to teach users about this point.

What you call strict mode (like in js) is default (see es6 modules for example). strict by default is better than loose by default.

**Comment by simonsmith** [comment]
Okay agreed.

So the solution is to add something like `strict: false` to the options to allow the behaviour @necolas and I are describing?

**Comment by MoOx** [comment]
Sounds good to me.
What about adding this in the README ?

---
## `strict` (default: true) 

By default, if fallbacks are used, a `var(...)` might be translated to several properties, with different values [to simulate specifications about invalid values](http://www.w3.org/TR/css-variables/#invalid-variables).
Setting to `false` will only keep latest computed value (in order to get a smaller output).

[More information about that behavior](https://github.com/postcss/postcss-custom-properties/issues/14).

**Comment by simonsmith** [comment]
+1 from me. Seems like a good compromise.

**Comment by necolas** [comment]
this should not be the default imo. the common case is for the behaviour that doesn't bloat the output with unused fallbacks.

**Comment by simonsmith** [comment]
I can see the logic in the existing approach but I do agree that ending up in a situation where you can have three `margin-bottom` declarations is perhaps taking spec adherence a bit far.

I suppose it depends where you draw the line on matching the spec.

**Comment by MoOx** [comment]
I will implement this as an option to avoid major release (for now).
If some others people come and complain about this I will set the option as default in a major release.

**Comment by necolas** [comment]
hmm, i'd be surprised if anyone is relying on this feature/regression in production.

**Comment by hgl** [comment]
I need this `strict: false` behavior for the extract option. Would be happy to implement it if I can it base on my PR (which changed the `resolveValue` function substantially).

Also I believe the current implementation isn't perfect:

```css
:root {
	--lineHeight: 1px;
}
body {
	margin: var(--lineHeight, 2px) var(--lineHeight, 2px);
}
```
=>
```css
body {
	margin: 2px 2px;
	margin: 2px 1px;
	margin: 1px 2px;
	margin: 1px 1px;
}
```

Should this be enough?

```css
body {
	margin: 2px 2px;
	margin: 1px 1px;
}
```

If you have an invalid value, the whole property is going to be ignored anyway.
