### ISSUE TITLE
don't warn of unexpandable (undefined) properties

### ISSUE THREAD

**Issue by drzraf** [postcss/postcss-custom-properties#149]
According to specification:
> Custom properties are ordinary properties, so **they can be declared on any element**, are resolved with the normal inheritance and cascade rules, can be made conditional with @media and other conditional rules, can be used in HTML’s style attribute, can be read or set using the CSSOM, etc.

I use this [CSS trick](https://www.bram.us/2017/07/30/vertical-marginspaddings-and-flexbox-a-quirky-combination/)
```css
@supports (--custom:property) {
    [style*="--aspect-ratio"]::before {
	content: "";
	display: block;
	padding-bottom: calc(100% / (var(--aspect-ratio)));
    }
}
```
In combination with:
`<div style="--aspect-ratio:1">`

But `postcss-custom-properties` then issues this warnings:
```
[1] undefined [undefined] [[repeated multiple times]]
[1] 45:2	⚠  variable '--aspect-ratio' is undefined and used without a fallback [postcss-custom-properties]
```

Defining a default value, whether from `:root`, from `postcss.config.js` or using `var()`'s second argument is not a solution because I want to preserver the expression as-is in the final CSS **but** just avoid this warning.
