### ISSUE TITLE
Variable scope issue

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-custom-properties#15]
input:

``` css
:root {
  --color: blue;
}
div {
  --color: green;
}
#alert {
  --color: red;
}
* {
  color: var(--color);
}
```

output(equate):

``` css
:root {
  color: blue;
}
div {
  color: green;
}
#alert {
  color: red;
}
```

html:

``` html
<p>I inherited blue from the root element!</p>
<div>I got green set directly on me!</div>
<div id='alert'>
While I got red set directly on me!
  <p>I’m red too, because of inheritance!</p>
</div>
```

http://dev.w3.org/csswg/css-variables/#syntax  example 5
