### ISSUE TITLE
importFrom not working

### ISSUE THREAD

**Issue by frippz** [postcss/postcss-custom-properties#152]
With reference to this closed issue: https://github.com/postcss/postcss-custom-properties/issues/141

I've got a similar setup, wherein I transpile separate files, so I gathered that `importFrom` was needed for `postcss-custom-properties` to work properly. My `postcss.config.js`:

```js
module.exports = {
  map: { inline: true },
  plugins: [
    require('postcss-custom-properties')({
      importFrom: 'src/css/00_variables.css'
    }),
  ]
};
```

Checking the output, however, shows this:

```css
#header {
  background-color: var(--header-background);
  background-color: var(--header-background);
  color: var(--header-text);
  color: var(--header-text);
  padding: 0;
}
```

This repo is [publicly available over here](https://github.com/frippz/frippz.se) should anyone want to have a closer look. Just to make sure that my config file was actually working, I quickly tested to add `preserve: false` which confirmed that it is (since those duplicated lines went away). Something might be off with the path, perhaps? I've tried both `importFrom: 'src/css/00_variables.css'` as well as `importFrom: './src/css/00_variables.css'`. The `src` folder does reside in the project root.
