### ISSUE TITLE
insert importedFrom into :root

### ISSUE THREAD

**Issue by RedHatter** [postcss/postcss-custom-properties#155]
I have a setup where I generate variables through a script then inject them using `importedFrom`. Unfortunately, `postcss-custom-properties` doesn't inject the newly generated variables into the `:root` declaration.

```js
// generate.js
module.exports = {
  customProperties: { '--main': 'red' }
}
```
```js
postcssCustomProperties({
  importFrom: 'generate.js'
});
```
Input css
```css
a {
  color: var(--main);
}
```
Output css
```css
a {
  color: red;
  color: var(--main);
}
```
What I would like
```css
:root {
  --main: red;
}

a {
  color: red;
  color: var(--main);
}
```
