### ISSUE TITLE
Variables within functions do not resolve

### ISSUE THREAD

**Issue by kaisellgren** [postcss/postcss-custom-properties#157]
It seems that variables are not resolved when used with functions such as:

```css
:root {
  --foo: hsl(200, 50%, 50%);
}

a {
  color: var(--foo);
}
```

The compiled output has `color: var(--foo);` but I expected to also see the actual color in the output for backwards compatibility for IE (IE does not support CSS variables).

**Comment by jonathantneal** [comment]
I tested the following CSS @ https://preset-env.cssdb.org/playground:

```css
:root {
  --foo: hsl(200, 50%, 50%);
}

a {
  color: var(--foo);
}
```

I set the `browserslist` to `ie >= 11` and observed the following result:

```css
:root {
  --foo: hsl(200, 50%, 50%);
}

a {
  color: hsl(200, 50%, 50%);
  color: var(--foo);
}
```

Is it possible that Internet Explorer usage has dropped globally to a point where you must force your browserslist to include support for it? I know I’ve had to explicitly add it for clients when their own analytics do not reflect global usage.
