### ISSUE TITLE
Incorrect output for undefined var (should be untouched)

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-properties#16]
``` css
* {
  background: linear-gradient(var(--a), var(--b));
}
```

gives

``` css
* {
  background: linear-gradient(linear-gradient(var(--a), var(--b)), , var(--b)));
}
```

This is totally unexpected :(
