### ISSUE TITLE
Remove :root in output file while preserve: false?

### ISSUE THREAD

**Issue by joe223** [postcss/postcss-custom-properties#160]
```css
:root {
  /** something **/
  --color: red;
}

h1 {
  color: var(--color);
}

/* becomes */
:root {
  /** something **/
}
h1 {
  color: red;
}
```
Can we just remove `:root` when it contain comments?
