### ISSUE TITLE
Feature request: disable preserve on a variable

### ISSUE THREAD

**Issue by mdmoreau** [postcss/postcss-custom-properties#163]
Somewhat related to https://github.com/postcss/postcss-custom-properties/issues/101.

Would it be possible to disable preserve on a single variable? I'm thinking maybe ```var()``` could be wrapped in another function that forces it to always write the actual variable value.

My use case is similar to the issue above, where I'm trying to use a var as a fill color in an SVG. Would something like ```n(var(--color))``` or ```nvar(--color)``` be within the scope of this plugin?

**Comment by homburg** [comment]
As a workaround, we're currently using `background-color: color-mod(--var-black)`, this results in the color output as a static value: `background-color: rgb(0, 0, 0)`

**Comment by garygreen** [comment]
@homburg that's an interesting concept. Maybe this library can provide a way of specifically hinting a variable should be converted to a static value?

```css
:root {
  --fa-search: "\F00D";
}
.my-icon {
   font-family: FontAwesome;
   content: static(var(--fa-search));
}
```

Expected output (even when `preserve=true`)

```css
.my-icon {
   font-family: FontAwesome;
   content: "\F00D";
}
```
