### ISSUE TITLE
css variable from imported files

### ISSUE THREAD

**Issue by iliakan** [postcss/postcss-custom-properties#167]
According to CSS vars draft, if I import a file with `:root` variables, it should work, right?
But it doesn't with postcss-custom-properties.

vars.css:
```css
:root {
  --some-color: red;
}
```
main.css:
```css
@import 'vars.css';

body {
  color: var(--some-color);
}
```

The variable doesn't get into `main.css`, is that a bug or a feature?
