### ISSUE TITLE
Having trouble setting options

### ISSUE THREAD

**Issue by brianzelip** [postcss/postcss-custom-properties#177]
Hello! I'm having trouble setting the `preserve` option. Anyone able to lend a hand? Here's my context:

I'm using postcss-cli to process some CSS:

```json
// package.json
{
 "scripts": {
    "build": "postcss src/palette.css -u postcss-import postcss-custom-media postcss-custom-properties postcss-calc postcss-color-function autoprefixer -d dist"
  }
}
```

```js
// postcss.config.js

module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-custom-media': {},
    'postcss-custom-properties': { preserve: false },
    'postcss-calc': {},
    'postcss-color-function': {},
    autoprefixer: {}
  }
};
```

```css
/* input */

body {
  font-family: var(--font-family);
  line-height: var(--line-height);
  font-size: var(--body-font-size);
}
```

Here's the output I expect:

```css
/* expected output */

body {
  font-family: 'Helvetica Neue', Helvetica, sans-serif;
  line-height: 1.5;
  font-size: 100%;
}
```

Yet here is the actual output:

```css
/* actual output */

body {
  font-family: 'Helvetica Neue', Helvetica, sans-serif;
  font-family: var(--font-family);
  line-height: 1.5;
  line-height: var(--line-height);
  font-size: 100%;
  font-size: var(--body-font-size);
}
```

I know this is a *really* basic question - thanks for any help!
