### ISSUE TITLE
Duplicated declaration without fallback

### ISSUE THREAD

**Issue by yoanmalie** [postcss/postcss-custom-properties#178]
Hi, weird new one I've found.

Input:
```css
img {
  --some-length: 32px;

  height: var(--some-length);
  width: var(--some-length);
}
```

Output:
```css
img {
  --some-length: 32px;

  height: var(--some-length);

  height: var(--some-length);
  width: var(--some-length);
  width: var(--some-length);
}
```

Expected:
```css
img {
  --some-length: 32px;

  height: 32px;
  height: var(--some-length);
  width: 32px;
  width: var(--some-length);
}
```
