### ISSUE TITLE
Variable replacement failure

### ISSUE THREAD

**Issue by geovezir** [postcss/postcss-custom-properties#188]
postcss-custom-properties@9.0.1

#### CSS input
```css
:root {
  --color1: #000000;
  --color2: #FFFFFF;
}

.success {
  background-image: linear-gradient(var(--color1), var(--color2));
}

.fail {
  background-image: linear-gradient(var(--color1),var(--color2));
}
```

#### CSS ouput ( preserve: false )
```css
.success {
  background-image: linear-gradient(#000000, #FFFFFF);
}

.fail {
  background-image: linear-gradient(#000000,var(--color2));
}
```

The variable is left unchanged if there is no space between the comma and the "var" keyword.
