### ISSUE TITLE
Plugin is removing comments after properties. 

### ISSUE THREAD

**Issue by creativesousa** [postcss/postcss-custom-properties#189]
I'm having an issue related to comments that are deleted when those are typed right after the property.

In my case, I need to use comments in order to use some RTLCSS features.

```css
:root {
    --spaceM: 1.5rem;
}

.title {
      left: calc(var(--gutter-M) * -1) /*rtl:ignore*/;
      font-size:16px/*rtl:14px*/;
}
```
Expected Output:

```css
.title {
      left: calc(1.5rem * -1) /*rtl:ignore*/;
      font-size:16px/*rtl:14px*/;
}
```
Actual Output:
```css
.title {
      left: calc(1.5rem * -1);
      font-size:16px/*rtl:14px*/;
}
```
Related issue: https://github.com/postcss/postcss-custom-properties/issues/86
Related Test: https://github.com/jonathantneal/postcss-tests/tree/master/postcss-custom-properties-test-00

Thanks for your amazing work with this awesome plugin.

Thanks in advance ;)
