### ISSUE TITLE
custom value for custom property

### ISSUE THREAD

**Issue by Diokuz** [postcss/postcss-custom-properties#192]
Hi there)

Im trying to upgrade _postcss-custom-properties_ from 7.0.0 to the latest version, and I have a problem.

I have a code:

```css
.defaultTheme {
  --FB-color-error-message: var(--color-red-bank);
}
```

which transpilled by 7th version to

```css
.defaultTheme {
  --FB-color-error-message: #f00 ;
}
```

but not by ^8.

PS: I've changed `variables: cssVariables,` to `importFrom: { customProperties: cssVariables },`, and it works for properties like `color`.

**Comment by thollander** [comment]
Hi, 

Facing the same problem here ... 
However, I saw that it seems to be wanted in [transform-properties.js#L43](https://github.com/postcss/postcss-custom-properties/blob/1e1ef6b1976d003d9491f46ceec1ba065e6afcba/src/lib/transform-properties.js#L43). 
Not sure why

**Comment by NXTaar** [comment]
Hi! A have the same problem. Need such functionality for proper theming.
my code
`colors.css`
```css
:root {
    --c-primary-bg: hsl(251, 80%, 88%);
    --c-primary: hsl(251, 78%, 40%);
    --c-primary-hover: hsl(251, 70%, 29%);
    --c-primary-pressed: hsl(238, 70%, 24%);

    --c-primary-alt-bg: hsl(0, 0%, 100%);
    --c-primary-alt-bg-hover: hsl(251, 30%, 96%);
    --c-primary-alt-bg-pressed: hsl(251, 27%, 92%);
}
```
`button.css`
```css
@import "../colors.css";
@import "../fonts.css";

.control {
    font: var(--font-primary);
    --btn-background:          var(--c-primary);
    --btn-background-hover:    var(--c-primary-hover);
    --btn-background-active:   var(--c-primary-pressed);
}
```

Import is resolved properly, but the result has same values, not replaced.

```css
.control {
    font: 400 16px/24px 'Helvetica Neue';
    --btn-background:          var(--c-primary);
    --btn-background-hover:    var(--c-primary-hover);
    --btn-background-active:   var(--c-primary-pressed);
}
```
