### ISSUE TITLE
Whitespace removed for variables followed by comma

### ISSUE THREAD

**Issue by dtothefp** [postcss/postcss-custom-properties#193]
When using variables for a CSS transition followed by a comma white space is removed between the transition properties which breaks the transition:

ex.
```css
// pre-compiled.css
:root {
  --transition-transform: transform 0.3s ease-out;
}

.bg {
  transition: var(--transition-transform), visibility 0.3s ease-out;
}
```

```css
// compiled css
:root {
  --transition-transform: transform 0.3s ease-out;
}

.bg {
  transition: transform0.3sease-out, visibility 0.3s ease-out;
  transition: var(--transition-transform), visibility 0.3s ease-out;
}
```

If a whitespace is added to the comma following the property the whitespace will be preserved

```css
// pre-compiled.css
:root {
  --transition-transform: transform 0.3s ease-out;
}

.bg {
  transition: var(--transition-transform) , visibility 0.3s ease-out;
}
```

```css
// compiled css
:root {
  --transition-transform: transform 0.3s ease-out;
}

.bg {
  transition: transform 0.3s ease-out , visibility 0.3s ease-out;
  transition: var(--transition-transform) , visibility 0.3s ease-out;
}
```
