### ISSUE TITLE
Feature request: rename custom properties for smaller bundle size

### ISSUE THREAD

**Issue by muuvmuuv** [postcss/postcss-custom-properties#194]
To reduce the size of a CSS file even more, I would love to see an option so that every custom property gets renamed to a small random unique string instead of the sometimes longer definitions.

So this:

```css
:root {
  --color-primary: #3f3f3f;
  --color-primary-dark: #2d2d2d;
}
button {
  background: var(--color-primary-dark);
  color: var(--color-primary);
}
```

would become:

```css
:root {
  --a: #3f3f3f;
  --b: #2d2d2d;
}
button {
  background: var(--b);
  color: var(--a);
}
```
