### ISSUE TITLE
Multiple font families separated with line breaks

### ISSUE THREAD

**Issue by otakustay** [postcss/postcss-custom-properties#196]
Without any options specified, with `postcss@7.0.21`, `postcss-cli@6.1.3` and `postcss-custom-properties@9.0.2`

```css
:root {
    --font-family: 'Courier New', Courier, monospace;
}

div {
    font-family: var(--font-family);
}
```

becomes:

```css
:root {
    --font-family: 'Courier New', Courier, monospace;
}

div {
    font-family: 'Courier New'
,
Courier
,
monospace;
    font-family: var(--font-family);
}
```

**Comment by tranlamnhatnam** [comment]
Same issue here!

Variable:
```css
:root {
  ...
  --btn-transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  ...
}

.btn:hover {
  ...
  transition: var(--btn-transition);
  ...
}
```

Output:
```css
.btn:hover {
  ...
  transition: color
.15s
ease-in-out
,
background-color
.15s
ease-in-out
,
border-color
.15s
ease-in-out
,
box-shadow
.15s
ease-in-out;
  transition: var(--btn-transition);
  ...
}
```
