### ISSUE TITLE
declaring variable as in postcss-preset-env example not working 

### ISSUE THREAD

**Issue by zanona** [postcss/postcss-custom-properties#200]
Under https://preset-env.cssdb.org/features#custom-properties
we have the following example:

```css
img {
  --some-length: 32px;

  height: var(--some-length);
  width: var(--some-length);
}
```

Although this doesn't seem to work and variables are not rewritten.
The only way to get this working was to define the variable under `:root`?

Perhaps I am missing something or can the example listed indeed be achieved?
Thanks
