### ISSUE TITLE
Comma-separated font-family declaration split onto multiple lines

### ISSUE THREAD

**Issue by MoltenCoffee** [postcss/postcss-custom-properties#221]
Hi there!
I'm encountering a weird issue that I cannot really pinpoint.

The setup is as follows:

```css
:root {
  --fontMain: "Open Sans", sans-serif;
}

body {
  font-family: var(--fontMain);
}
```

After running PostCSS (for which I have gulp setup, I run PostCSS-custom-properties with default settings), the resulting CSS is this:

```css
:root {
  --fontMain:"Open Sans",sans-serif;
}
/* Notice the weird spacing of the first font-family property in body: */
body {
  font-family:"Open Sans"
,
sans-serif;
  font-family:var(--fontMain);
}
```

I believe this should work in the browser, and a minifier further down the line will probably solve it, but this seems weird behaviour to me. Any idea what causes this?
Disabling all other postCSS plugins yields the same result.
