### ISSUE TITLE
Variables starting with '-' cannot be recognized

### ISSUE THREAD

**Issue by chenyulun** [postcss/postcss-custom-properties#239]
```js
const postcss = require("postcss");
const postcssCustomProperties = require("postcss-custom-properties");

const testStr = `
:root {
  ---first-color: 255, 255, 0;
  --second-color: rgba(var(---first-color), .5);
}
h1 {
  color: var(--second-color);
}
`;
postcss([
  postcssCustomProperties({
  }),
])
  .process(testStr, { from: 'src/app.css', to: 'dest/app.css' })
  .then((result) => {
    console.log(result.css);
  });
```
output css
```css
:root {
  ---first-color: 255, 255, 0;
  --second-color: rgba(var(---first-color), .5);
}
h1 {
  color: rgba(var(---first-color), .5);
  color: var(--second-color);
}
```
The browser should work
