### ISSUE TITLE
:root selector remains post processing

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#38]
Hi,

I have the following:

```css
:root {
/* 2a */
  --font-size-root: 16px;
}
html {
/* 2b */
  font-size: var(--font-size-root);
}
```

After processing it looks like this:

``` css
:root {
/* 2a */
}
html {
/* 2b */
  font-size: 16px;
}
```

The gulptask I'm using looks like this (In case it makes a difference):

```js
var processors = [postcss_import, autoprefixer, postcss_calc, postcss_custom_properties, postcss_color_function];

gulp.task('build:css', ['clean'], function() {
  return gulp.src(PLI.SRC_MAIN_CSS)
    .pipe(postcss(processors))
    .pipe(gulp.dest(PLI.target.main.css));
});
```
