### ISSUE TITLE
Output has Duplicate Empty Property when Using `var()`

### ISSUE THREAD

**Issue by ryanfitzer** [postcss/postcss-custom-properties#42]
Using the default configuration, I'm getting a duplicate property with an empty value.

Before:

```css
a {
    color: var( --global-color-links );
}
```

After:

```css
a {
    color:  ;
    color: #c53e3e;
}
```
