### ISSUE TITLE
Font stacks break when combined

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-custom-properties#46]
This could be the spec, but here's example.

```css
:root {
  --BorderStyle: solid;
  --BorderWidth: 2px;

 --DefaultBorderProperties: {
     border: var(--BorderWidth) var(--BorderStyle);
     border-radius: var(--BorderRadius);
  }
}
```
Outputs exactly how you'd expect:
```css
    border: 2px solid;
```

But: 
```css
:root
 --FallbackFontFamily: "Helvetica Neue", Helvetica, -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",  sans-serif;
 --LightFontFamily: "Helvetica Neue Light", HelveticaNeue-Light;
```

```fonts.csss
.buttonLabel {
  font-family: var(--LightFontFamily) var(--FallbackFontFamily);
}
```
Output:

```css
.buttonLabel {
    font-family: --FallbackFontFamily;  ❌ 
    font-family: "Helvetica Neue Light", HelveticaNeue-Light;
```

**Comment by MoOx** [comment]
The following code is totally working in the playground http://cssnext.io/playground/

```css
:root {
 --FallbackFontFamily: "Helvetica Neue", Helvetica, -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",  sans-serif;
 --LightFontFamily: "Helvetica Neue Light", HelveticaNeue-Light;
}
.buttonLabel {
  font-family: var(--LightFontFamily) var(--FallbackFontFamily);
}
```

And gives this

```css
.buttonLabel {
  font-family: "Helvetica Neue Light", HelveticaNeue-Light "Helvetica Neue", Helvetica, -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",  sans-serif;
}
```

You probably have another problem before (I can notice your stacks definition are not in braces).
