### ISSUE TITLE
Custom properties inside classes

### ISSUE THREAD

**Issue by lukasoppermann** [postcss/postcss-custom-properties#47]
Hey,

if I am not mistaken the following should be possible (currently works in chrome).

```css
.class{
  --color: red;
  color: var(--color);
}
```

However it is currently not supported in this plugin. Any reason? Could you support it? This would be awesome for conditional styling, e.g. notices with states like `.error`, `.warning`, etc.
