### ISSUE TITLE
Fallback Value

### ISSUE THREAD

**Issue by chrismbeckett** [postcss/postcss-custom-properties#51]
Any plans to support fallback value for cascading variables? Without the fallback values, you have to define and import every variable in root for every component in your application.

```css
.component .header {
  color: var(--header-color, blue);
}
```
