### ISSUE TITLE
Concatenation support

### ISSUE THREAD

**Issue by stevenvachon** [postcss/postcss-custom-properties#52]
```css
:root {
  --test: "test";
}

element::before {
  content: "(" var(--test) ")";
}
```
produces:
```css
element::before {
  content: "(" "test" ")";
}
```
when it should *probably* (?) produce:
```css
element::before {
  content: "(test)";
}
```

This causes an issue for me with URLs:
```css
:root {
  --test: "path/to/";
}

element {
  background-image: url( var(--test) "image.svg" );
}
```

**Comment by MoOx** [comment]
If that's in the spec, then PR welcome, if not, maybe use another plugin.

**Comment by stevenvachon** [comment]
I'm not sure if it is.. specs are always unclear to me.

**Comment by jescalan** [comment]
I have the same use-case here, need to prefix image paths with a configurable base URL. Does anyone have a solution to this issue? I managed to get the single property working with `background: url(var(--baseUrl)path/to/image.png)`, but it causes the rest of the css to be incorrectly parsed so something is definitely getting screwed up.

**Comment by MoOx** [comment]
var() depend on the dom. an url can't depend on the dom state, this is crazy. It's just not in the spec and won't be.

**Comment by stevenvachon** [comment]
@MoOx please reopen this.

https://drafts.csswg.org/css-variables/#example-97d3694f

**Comment by MoOx** [comment]
Pretty sure this will never work for url(). Can't find it but I have a discussion with tabatkins I think about that. So please ask specs writers or mailing list, then I will reopen if you have more materials.

**Comment by jescalan** [comment]
@tabatkins would you be able to weigh in if you have a chance?

The tl;dr on the issue here is whether it's possible to concatenate css variables with other information. For example, if one were to have a css variable representing a base path for images, would it be possible to add this variable as a path prefix? Like:

```css
.somediv {
  background: url(var(--basePath) '/foo.jpg')
}
```

**Comment by stevenvachon** [comment]
@MoOx this issue is not just for `url()`, but `content` as well as per my original comment.

**Comment by MoOx** [comment]
Right my bad.

**Comment by tabatkins** [comment]
Just sub in the value; if it works directly, you're good.

So in the url() case, `url("foo/" "bar")` doesn't work, so it won't work with `var()` either.

On the other hand, `content: "foo" "bar";` does work just fine, so it works with `var()` too.  `content` explicitly takes multiple strings and concats them for you.

We can't add the auto-concat functionality in general, because there are properties that legitimately take adjacent strings, like ['quotes'](https://www.w3.org/TR/CSS22/generate.html#propdef-quotes).

We could add a `string-concat()` function to make this work everywhere, but it still wouldn't work *in `url()`*, because `url()` is FUBAR and has [a special parsing routine](https://drafts.csswg.org/css-syntax/#consume-url-token) to allow the no-quotes syntax. Any value that doesn't start with a quote mark is assumed to be a url we try to parse, so `url(string-concat("foo/", var(--bar)))` will just start trying to parse the contents as a url, then see the quote mark and freak out, treating the whole thing as an invalid url token.

The only way to work around the url issue is to have a new function entirely that just parses as an ordinary function, so you could use functions and whatnot inside of them safely.

**Comment by MoOx** [comment]
Thanks for the clarification @tabatkins.

So @stevenvachon your first example already works as expected, and the second can't just from this plugin.

**Comment by jescalan** [comment]
So would a plugin [like this](https://github.com/postcss/postcss-url) be the best option for url prefixing?

**Comment by stevenvachon** [comment]
This is why I'm still use less/sass. I can't use `postcss-url` because I have multiple bases (CDN and relative).

**Comment by jescalan** [comment]
Another small postcss plugin could easily solve this issue, no? In theory it could even be configured with the name of a url-postfix and a prefix string, like:

```js
postcssUrlPrefix({
  cdn: 'https://cdn.com/',
  somethingElse: 'https://something.com/'
})
```

```css
div {
  background: cdn-url('image.jpg')
}
```
