### ISSUE TITLE
Periods do not work in variable names

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#63]
## Variable:
:root {
  --Button.onDisabled-opacity: 0.6;
}

## Template definition:
``` css
.Button.onDisabled {
  cursor: default;
  opacity: var(--Button.onDisabled-opacity);
}
```

## Rendering

``` css
.Button.onDisabled {
  opacity: .onDisabled-opacity;
}
```

I asked on [SO if periods are allowed per the specification](http://stackoverflow.com/questions/42215415/are-periods-allowed-in-css-variable-names)

To reproduce the above description:
``` console
git clone git clone git@github.com:superfly-css/superfly-css-component-button.git
cd superfly-css-component-button
npm install
gulp build:css
cat target/main/css/index.css

```
