### ISSUE TITLE
Line breaks inside nested fallbacks unduly cause a syntax error

### ISSUE THREAD

**Issue by chris-morgan** [postcss/postcss-custom-properties#70]
Minimum viable example:

```css
:root {
    foo: var(--a, var(--b,
0));
}
```

> `CssSyntaxError: postcss-custom-properties: <css input>:2:5: missing closing ')' in the value 'var(--b,' 1 | :root { > 2 | foo: var(--a, var(--b, | ^ 3 | 0)); 4 | }`

Remove the line break and it works. Remove the outer level of `var()` wrapping and it works.

---

Furthermore, that this compiles:
```css
:root {
    foo: var(--a, 0)))))))));
}
```
to this:
```css
:root {
    foo: 0))))))));
}
```
also worries me. Both, I presume, are symptoms of the data not being handled as proper parsed function call syntax, but rather as strings being pulled apart in hazardous ways.

**Comment by chris-morgan** [comment]
It doesn’t need to be nested fallbacks, just nested parentheses:

Input:
```css
a {
b: var(--c,
d(e
f));
}
```
Expected output:
```css
a {
b: d(e
f);
}
```
Actual output:
```css
a {
b: d(e;
}
```

----

This is forcing me to depart from my CSS style guide and end up with messy things lines like this:

```css
foo:hover {
    background-image: var(--foo-hover-background-image,
        linear-gradient(var(--foo-hover-color-1, color(var(--foo-color-1) l(+5%))), var(--foo-hover-color-2, color(var(--foo-color-2) l(+5%)))));
}
```

instead of slightly more elegant things like

```css
foo:hover {
    background-image: var(--foo-hover-background-image,
        linear-gradient(
            var(--foo-hover-color-1, color(var(--foo-color-1) l(+5%))),
            var(--foo-hover-color-2, color(var(--foo-color-2) l(+5%)))
        )
    );
}
```
