### ISSUE TITLE
Custom function name conflict

### ISSUE THREAD

**Issue by ambar** [postcss/postcss-custom-properties#82]
Input

```css
a { color: myvar(RED); }
```

Output:

```
{
  "type": "warning",
  "text": "variable 'RED' is undefined and used without a fallback",
}
```
