### ISSUE TITLE
Plugin is remove comments and it shouldn't do it.

### ISSUE THREAD

**Issue by sandrina-p** [postcss/postcss-custom-properties#86]
Hey, thanks for your plugin, is amazing!

So, I'm having an issue related to comments that are deleted when those are typed inside the property value. 

In my case, I need to use `comments` in order to use some [RTLCSS](rtlcss.com) features.

```scss
:root {
    --clrPrimary: red;
}

.title {
      color: var(--clrPrimary)/*rtl:inherit*/;
      font-size:16px/*rtl:14px*/;
}
```

**Expected Output:**
```scss
.title {
      color: red/*rtl:inherit*/;
      font-size:16px/*rtl:14px*/;
}
```

**Actual Output:**
```scss
.title {
      color: red;
      font-size:16px/*rtl:14px*/;
}
```

Would it be possible to fix that?

Thank you 😄
