### ISSUE TITLE
Investigate support for media-query scoped properties

### ISSUE THREAD

**Issue by necolas** [postcss/postcss-custom-properties#9]
See: https://github.com/reworkcss/rework-vars/issues/17. I still think this is inherently problematic (like plugins that consolidate media queries), but worth exploring to get an answer.

Example input:

``` css
:root { --fontSize: 2em; }
.Section { font-size: var(--fontSize); }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
}
```

Example output:

``` css
.Section { font-size: 2em; }

@media (min-width: 64em) {
  .Section { font-size: 3em; }
}
```

Complications could include:
- inlined `@import` statements in media queries
- not knowing the relationship between different media queries (might generate extra CSS rules that aren't needed, e.g., what if the MQ is `@media screen (min-width:0)`?)
- generating large amounts of extra CSS
- specificity/cascade issues - moving/generating rules is always going to hit the problem where earlier styles are unintentionally overridden.

``` html
<div class="One Two">Text</div>
```

Input:

``` css
:root { --fontSize: 2em; }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
}
```

Output (notice `One` now overrides `Two`, which it would not with a native solution):

``` css
.One { font-size: 2em; }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  .One { font-size: 3em; }
}
```

**Comment by hgl** [comment]
Can we add an option to allow this type of media scoped variables?

Input
```css
:root { --fontSize: 2em; }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
  .One { font-size: var(--fontSize); }
}
```
=>
```css
.One { font-size: 2em; }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  .One { font-size: 3em; }
}
```

In this case, the author manually add the rule to `@media` to promise cssnext that specificity won't be an issue.

And with this option enabled, if they give an input:

```css
:root { --fontSize: 2em; }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
}
```
we only produce
```css
:root { --fontSize: 2em; }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }
```

This isn't spec compliant, but this option defaults to false, and authors who enable it should know how it actually works. Note that although the option itself isn't spec compliant, giving it the correct input, it will generate spec compliant code.

The reason I want this behavior is that if I put all variables in the top level, naming becomes very painful:

```css
:root { --fontSize: 2em; --wideViewFontSize: 3em }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  .One { font-size: var(--wideViewFontSize); }
}
```

Tons of variables need to be fixed with `wideView`. length isn't the only problem. Imagine a variable that only make sense in a wide view, now should you prefix the name with `wideView`? With scoped variables, the problems go away.

**Comment by hgl** [comment]
But there is probably one problem: passing js defined custom properties and extracting custom properties is not as simply as it current does.

I can think of a few solutions:

- js defined custom properties only apply to the top level
- js defined custom properties must be defined like this

  ```json
  {
    "": { "width": "1em" },
    "(width >= 960px)": { "width": "2em" }
  }
  ```

  Media queries must match exactly for the custom properties to be applied, making things simple.
- custom properties are extracted as above

**Comment by MoOx** [comment]
Both solutions are dangerous. I don't think we should implement partial & weird solutions.

Maybe you can "just" use a shorter convention for size like I do

```css
:root {
  --fontSize: 2em;
  --fontSize--XL: 3em; /* i use xs, s, m, l, xl */
}
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  .One { font-size: var(--fontSize--XL); }
}
```

**Comment by hgl** [comment]
A bit cryptic IMHO. But I agree the option is dangerous. I'm looking at shadow dom now to see if it can help.

**Comment by MoOx** [comment]
@necolas what do you think about the solution below (injecting rules after the selector using the custom prop) ?
Someone opened an issue on cssnext #https://github.com/cssnext/cssnext/issues/99 with this solution and with a quick test it seems it is working as native custom props.

```html
<div class="One Two">Text</div>
```

Input:

```css
:root { --fontSize: 2em; }
.One { font-size: var(--fontSize); }
.Two { font-size: 6em; }

@media (min-width: 64em) {
  :root { --font-size: 3em; }
}
```

Output:

```css
.One { font-size: 2em; }
@media (min-width: 64em) { /* this do not override selector below */
  .One { font-size: 3em; }
}

.Two { font-size: 6em; }
```
