### ISSUE TITLE
Output with preserve and color function

### ISSUE THREAD

**Issue by Hilzu** [postcss/postcss-custom-properties#99]
I have CSS like this:

```css
:root {
  --brand: #00bdbd;
  --dark-brand: color(var(--brand) shade(20%));
}

.bg-brand {
  background-color: var(--brand);
}

.bg-dark-brand {
  background-color: var(--dark-brand);
}
```

I'm using the `postcss-color-function` plugin to transform the color function. I've configured custom-properties to run before the color function plugin as [recommended in its readme](https://github.com/postcss/postcss-color-function#can-we-use-css-custom-properties-so-we-can-do-colorvar--maincolor-adjuster).

With the new `postcss-custom-properties` that has the `preserve` option set to `true` generates this output that doesn't work in any browser:

```css
:root {
  --brand: #00bdbd;
  --dark-brand: rgb(0, 151, 151);
  --dark-brand: color(var(--brand) shade(20%));
}

.bg-brand {
  background-color: #00bdbd;
  background-color: var(--brand);
}

.bg-dark-brand {
  background-color: rgb(0, 151, 151);
  background-color: var(--dark-brand);
}
```

Here's a runkit notebook that generates this same output: https://runkit.com/hilzu/postcss-custom-properties-with-preserve-enabled

Is it so that the preserve option can't be used when using color functions with variables?
